name: DevSecOps-Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK (Sonar requirement)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Python Script
        run: python3 hello.py
      - name: Run Sonar Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=girish-potnuru_devsecops-demo-
            -Dsonar.organization=girish-potnuru
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pip-audit (isolated venv)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv .venv-pip-audit
          source .venv-pip-audit/bin/activate
          pip install --upgrade pip
          pip install pip-audit
          pip-audit -r requirements.txt --desc
          deactivate

      - name: Run Safety Scan
        run: |
          pip install safety
          safety check --full-report
      - name: Security Placeholder
        run: echo "üîê Security Scan will be added here later"
